[platformio]
default_envs = left, right

[env]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
extra_scripts = pre:scripts/wifi_config.py
lib_deps =
    fastled/FastLED@3.6.0
    links2004/WebSockets@2.4.1
lib_ignore = ServoController

[env:left]
build_flags = -Iinclude -D OCTACORE_ROLE=\"left\" -D OCTACORE_TOWER_ID=1

[env:right]
build_flags = -Iinclude -D OCTACORE_ROLE=\"right\" -D OCTACORE_TOWER_ID=2

[env:tower1]
build_flags = -Iinclude -D OCTACORE_ROLE=\"1\" -D OCTACORE_TOWER_ID=1

[env:tower2]
build_flags = -Iinclude -D OCTACORE_ROLE=\"2\" -D OCTACORE_TOWER_ID=2

[env:tower3]
build_flags = -Iinclude -D OCTACORE_ROLE=\"3\" -D OCTACORE_TOWER_ID=3

[env:tower4]
build_flags = -Iinclude -D OCTACORE_ROLE=\"4\" -D OCTACORE_TOWER_ID=4
