[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
lib_ldf_mode = deep+
lib_ldf_mode = deep+
build_flags =
    -I include
    -I lib/LEDStripController
    -I lib/ServoController
    -I lib/WifiModule
    -I lib/WebSocketModule
    -I lib/WebSocketEvents
extra_scripts =
    pre:scripts/generate_env_header.py

lib_deps =
    fastled/FastLED@^3.6.0
    madhephaestus/ESP32Servo@^1.1.2
    wnatth3/WiFiManager@^2.0.16-rc.2
    links2004/WebSockets@^2.4.1
